### PR TITLE
bump to 0.24.7

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by cwognum** [comment]
Could this be a broken version... ?

Once I install it with `conda`, I get a long stacktrace ending with:
```
jinja2.exceptions.TemplateNotFound: mkdocs_html/assets/index.css
```

Listing all files in that directory, only shows: 
```
>>> ls .../mkdocs_html/assets/index.css
clipboard.umd.js
```

After removing the package and reinstalling it with pip, I get:
```
>>> ls .../mkdocs_html/assets/index.css
clipboard.umd.js dark.js          index.css        index.js         light.js         theme-dark.css   theme-light.css
```

Manually downloading the `.tar.gz` for `0.24.6` from the Github releases, the files are missing. Downloading the `.tar.gz` for that same version manually from PyPi does include the files.

I'm a little confused what's happening here!

**Comment by cwognum** [comment]
It seems `mkdocs-jupyter` uses [`rye`](https://rye-up.com/) for releasing, but also has a step specific to the Javascript parts which uses [`pnpm`](https://github.com/pnpm/pnpm) (see [`RELEASE.md`](https://github.com/danielfrg/mkdocs-jupyter/blob/main/RELEASE.md)). This could explain why Github releases and PyPi packages are not the same. The Github release doesn't include the generated HTML / CSS / JS files.

**Comment by cwognum** [comment]
Should probably wait on a response on https://github.com/danielfrg/mkdocs-jupyter/issues/197. 

Ping @danielfrg.

**Comment by hadim** [comment]
I think hatch is used for the build but the issue seems to be missing files during the release (managed by rye?).

**Comment by hadim** [comment]
I asked for the package to be moved to broken: https://github.com/conda-forge/admin-requests/pull/982

I won't have time to work on a fix for this. I suggest working with the upstream maintainer or finding a fix during the build (calling pnpm or something).

**Pull request merged**
