### PR TITLE
Bump version and add bot updates

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 234, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 216, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - python >=3.7
 - poetry >=1.2.0a2
 - pip
 - setuptools >=57,<58

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested poetry >=1.2.0a2
```


This is blocked by poetry. We need to wait for poetry 1.2.0 to be released.

**Comment by cpcloud** [comment]
> ```
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
>     solution = solver.solve_for_action(_specs, prefix)
>   File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 234, in solve_for_action
>     t = self.solve(specs)
>   File "/opt/conda/lib/python3.9/site-packages/boa/core/solver.py", line 216, in solve
>     raise RuntimeError("Solver could not find solution." + error_string)
> RuntimeError: Solver could not find solution.Mamba failed to solve:
>  - python >=3.7
>  - poetry >=1.2.0a2
>  - pip
>  - setuptools >=57,<58
> 
> with channels:
> 
> The reported errors are:
> - Encountered problems while solving:
> -   - nothing provides requested poetry >=1.2.0a2
> ```
> 
> This is blocked by poetry. We need to wait for poetry 1.2.0 to be released.

There's an upstream change to make `mkdocs-jupyter` work with released versions of poetry, so I think we just need to wait for @danielfrg to cut a release.

**Comment by danielfrg** [comment]
I just released `0.20.0` , that should fix this issue

**Comment by hadim** [comment]
Thank you @danielfrg 

@cpcloud do you  want to be added as a maintainer?

**Comment by cpcloud** [comment]
@hadim Sure thing!

**Pull request merged**
